### PR TITLE
scaffold RentalUnitModel into RentalModel

### PR DESCRIPTION
**Pull request by elmertsai**
Fixed Issue #77
Tests are functional, but need to move validation attributes to custom attribute folder.

Note:
1) Current seeded RentalModels in Context fail the validation criteria (e.g. Size is "5x5" but need to be "5[Unit]x5[Unit]") so need to be fixed.
2) Need to include "bad cases" for test method to ensure validation is properly working

### CODE REVIEW

**Comment by elmertsai** [comment]
Full fix of issue #77 with this commit.

Consider opening new issues to fix seeded data and more robust testing

**Comment by elmertsai** [comment]
TODO:
need to add testing to custom attribute IsValid methods to ensure code coverage pass the quality gate

**Comment by fredbelotte** [comment]
as discussed, we need to meet higher code coverage? let's do this.

**Comment by elmertsai** [comment]
Added testing for the overridden IsValid method in the custom validation attributes for properties of RentalModel.

**Comment by elmertsai** [comment]
This is ready for review

**Review by fredbelotte — APPROVED** [review]
add new issue to handle encapsulation of attribute validation.

**Pull request merged**
